# This is a sample build configuration for Go.
# Check our guides at https://confluence.atlassian.com/x/5Q4SMw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: golang:1.9

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          - git config --global url."git@bitbucket.org:".insteadOf "https://bitbucket.org/"
          - PACKAGE_PATH="${GOPATH}/src/bitbucket.org/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}"
          - mkdir -pv "${PACKAGE_PATH}"
          - tar -cO --exclude-vcs --exclude=bitbucket-pipelines.yml . | tar -xv -C "${PACKAGE_PATH}"
          - cd "${PACKAGE_PATH}"
          - REPO=bitbucket.org/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}
          - go get -v ${REPO}/pkg/{semix,index,query,rdfxml,turtle,resource,rule,rest,resolve}
          - go get -v ${REPO}/cmd/semix-{httpd,daemon,crawl,client,wiki}
          - go build -tags isize1 ${REPO}/pkg/index
          - go test -cover -race -tags isize1 ${REPO}/pkg/index
          - go build -tags isize2 ${REPO}/pkg/index
          - go test -cover -race -tags isize2 ${REPO}/pkg/index
          - go build -tags isize3 ${REPO}/pkg/index
          - go test -cover -race -tags isize3 ${REPO}/pkg/index
          - go build -tags isize4 ${REPO}/pkg/index
          - go test -cover -race -tags isize4 ${REPO}/pkg/index
          - go build -tags isize5 ${REPO}/pkg/index
          - go test -cover -race -tags isize5 ${REPO}/pkg/index
          - go build -v ${REPO}/pkg/{semix,index,query,rdfxml,turtle,resource,memory,rule,rest,resolve}
          - go build -v ${REPO}/cmd/semix-{httpd,daemon,crawl,client,wiki}
          - go test -race -cover ${REPO}/pkg/{semix,index,query,rdfxml,turtle,resource,memory,rule,rest,resolve}
