# This is a sample build configuration for Go.
# Check our guides at https://confluence.atlassian.com/x/5Q4SMw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: golang:1.9

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          - git config --global url."git@bitbucket.org:".insteadOf "https://bitbucket.org/"
          - PACKAGE_PATH="${GOPATH}/src/bitbucket.org/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}"
          - mkdir -pv "${PACKAGE_PATH}"
          - tar -cO --exclude-vcs --exclude=bitbucket-pipelines.yml . | tar -xv -C "${PACKAGE_PATH}"
          - cd "${PACKAGE_PATH}"
          - REPO=bitbucket.org/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}
          - go get -v ./...
          - go get -u github.com/golang/lint/golint
          - golint ./...
          - go vet ./...
          - go test -cover ./...
          - >-
            for s in 1 2 3 4 5; do
                go test -cover GOTAGS="tags isize$s" ./...
            done
          # - make test
          # - make test GOTAGS='-tags isize1'
          # - make test GOTAGS='-tags isize2'
          # - make test GOTAGS='-tags isize3'
          # - make test GOTAGS='-tags isize4'
          # - make test GOTAGS='-tags isize5'
          # - make install
          # - if test "${BITBUCKET_BRANCH}" = "master"; then make upload AUTH=${SEMIX_AUTH}; fi
